baseURL = ""
languageCode = "en-us"
title = "Resume"
disableKinds = ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme = "resume-a4"

[params]
useFontAwesome = true
avatar = "avatar.jpg"
bib_style = "IEEE" # IEEE, APA, else

[params.display]
experience = true
about_me = true
languages = true
skills = true
interests = true
education = true
tagline = true
avatar = true

[params.title_as]
about_me = "Personal Information"
experience = "Personal Info"
education = "Education"
languages = "Languages"
skills = "Skills"
interests = "Interests"

[params.display.footer]
footer = true
links = true
credits = true

[params.footer]
footnote = "Last update on 29.02.2026."

[params.footer.links]
[[params.footer.links.link]]
prefix = "You can find me on"
name = "Instagram"
url = "https://instagram.com/bllyz"
icon = "fab fa-instagram"

[[params.footer.links.link]]
prefix = "Check out my"
name = "Music"
url = "https://biglink.to/bllyz"
icon = "fas fa-music"
